{
 "title": "Kafka Consumers / Fetch Rate & Records Lag",
 "tags": [
  "kafka",
  "clients"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "topic",
    "query": "net_coru_kloadgen_bank_movement, net_coru_kloadgen_bank_account"
   },
   {
    "name": "destination_topic",
    "label": "Destination Topic",
    "query": "net.coru.kloadgen.bank.movement, net.coru.kloadgen.bank.account"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Client Lag",
   "type": "graph",
   "description": "The latest lag of each client",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate{topic=\"$topic\"}) by(topic, client_id, instance)",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Fetch Bytes Per Request",
   "type": "graph",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_size_avg{topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Consumed Bytes Rate Per Second",
   "type": "graph",
   "description": "The average number of bytes consumed per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate{topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Consumed Records Rate Per Second",
   "type": "graph",
   "description": "The average number of records consumed per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_count{name=\"KafkaConsumerDestination{consumerDestinationName='$destination_topic', partitions=1, dlqName='null'}.container-0\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}