{
 "title": "Bank Demo",
 "description": "Kloadgen Bank Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Account & Movements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Updated Bank Account",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bank_account_updated_seconds_count[1m])",
     "legendFormat": "Accounts updated"
    }
   ]
  },
  {
   "title": "Processed Bank Account",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(bank_account_processed_total[$__rate_interval])",
     "legendFormat": "Movements Processed"
    }
   ]
  },
  {
   "title": "Bank Account Emitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(bank_account_emitted_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Services Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "used bytes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "CPU usage" }
   ]
  },
  {
   "title": "Mongo times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_driver_commands_seconds_sum[$__range]) / rate(mongodb_driver_commands_seconds_count[$__range])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}