{
 "title": "Kafka Topics / Logs",
 "tags": [
  "kafka",
  "topics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_log_size, env)"
    }
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": "net.coru.kloadgen.bank.account, net.coru.kloadgen.bank.movement"
   }
  ]
 },
 "panels": [
  {
   "title": "$topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "topic",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Log Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_size{env=\"$env\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Total Number of Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"partition\", kafka_log_numlogsegments{topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Number of Partitions Under Min ISR",
   "type": "stat",
   "description": "should alert if > 0",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{env=\"$env\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "should alert if > 0",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{env=\"$env\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Number of Segment Files Per Broker",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_log_numlogsegments{topic=\"$topic\", env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Messages In Per Sec (OneMinuteRate)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_broker_topic_metrics_messagesinpersec_rate{topic=\"$topic\", env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BytesInPerSec (OneMinuteRate)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_broker_topic_metrics_bytesinpersec_rate{topic=\"$topic\", env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BytesOutPerSec (OneMinuteRate)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_broker_topic_metrics_bytesoutpersec_rate{topic=\"$topic\", env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}