{
 "title": "Kafka / Brokers JVM & OS",
 "description": "Java Virtual Machine Memory and OS metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": "cluster-demo" }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Used (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_non_heap_usage{env=\"$env\", type=\"used\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "JVM Memory Used (Heap)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_heap_usage{env=\"$env\", type=\"used\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_os_systemcpuload{env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_os_processcpuload{env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_os_openfiledescriptorcount{env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "graph",
   "description": "The amount of free physical memory in bytes.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_os_freephysicalmemorysize{env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Virtual Memory",
   "type": "graph",
   "description": "The amount of virtual memory that is guaranteed to be available to the running process in bytes",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_os_committedvirtualmemorysize{env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}